window.PRIMEQK_CLIENT_CONFIG = {
  productKey: "plus",
  productName: "素数大富豪＋",
  lobbyName: "Classic / Plus ロビー",
  wsUrl: "wss://web-production-c8e68.up.railway.app/ws/plus",
  shareUrl: "https://greenplus.github.io/qkplus/",
  maxRoomPlayers: 10,
  defaultRoomGroupKey: "classic",
  defaultRoomKey: "classic1",
  roomGroupOrder: ["classic", "plus"],
  roomGroups: {
    classic: {
      label: "Classic",
      roomKeys: ["classic1", "classic2", "classic3", "classic4", "classic5", "classic6"],
    },
    plus: {
      label: "Plus",
      roomKeys: ["plus1", "plus2", "plus3", "plusTournament"],
    },
  },
  rooms: {
    classic1: {
      roomId: "room_1",
      roomGroupKey: "classic",
      roomNumber: 1,
      label: "Classic",
      title: "5枚",
      summary: "ペナルティ1枚",
      badge: "5枚 / ペナルティ1枚",
    },
    classic2: {
      roomId: "room_2",
      roomGroupKey: "classic",
      roomNumber: 2,
      label: "Classic",
      title: "7枚 / 偶数半減",
      summary: "ペナルティ1枚",
      badge: "7枚 / 偶数半減 / ペナルティ1枚",
    },
    classic3: {
      roomId: "room_3",
      roomGroupKey: "classic",
      roomNumber: 3,
      label: "Classic",
      title: "7枚",
      summary: "ペナルティ1枚",
      badge: "7枚 / ペナルティ1枚",
    },
    classic4: {
      roomId: "room_4",
      roomGroupKey: "classic",
      roomNumber: 4,
      label: "Classic",
      title: "11枚",
      summary: "ペナルティは場の枚数",
      badge: "11枚 / ペナルティは場の枚数",
    },
    classic5: {
      roomId: "room_5",
      roomGroupKey: "classic",
      roomNumber: 5,
      label: "Classic",
      title: "11枚 / 通常",
      summary: "合成数あり",
      badge: "11枚 / 通常 / 合成数あり",
    },
    classic6: {
      roomId: "room_6",
      roomGroupKey: "classic",
      roomNumber: 6,
      label: "Classic",
      title: "11枚 / 通常",
      summary: "合成数なし",
      badge: "11枚 / 通常 / 合成数なし",
    },
    plus1: {
      roomId: "room_7",
      roomGroupKey: "plus",
      roomNumber: 1,
      label: "Plus",
      title: "初期革命",
      summary: "11枚 / 通常",
      badge: "初期革命 / 11枚 / 通常",
    },
    plus2: {
      roomId: "room_8",
      roomGroupKey: "plus",
      roomNumber: 2,
      label: "Plus",
      title: "四つ子素数",
      summary: "11枚 / 通常",
      badge: "四つ子素数 / 11枚 / 通常",
    },
    plus3: {
      roomId: "room_9",
      roomGroupKey: "plus",
      roomNumber: 3,
      label: "Plus",
      title: "半素数",
      summary: "11枚 / 通常",
      badge: "半素数 / 11枚 / 通常",
    },
    plusTournament: {
      roomId: "plus_tournament_1",
      roomGroupKey: "plus",
      roomNumber: "大会",
      label: "Plus",
      title: "定期大会",
      summary: "日程・ルールは大会ごとに設定",
      badge: "システム進行の定期大会",
      tournament: true,
    },
  },
  defaultSampleKey: "",
  features: {
    assist: false,
    registration: false,
    hnpChallenge: false,
    campaign: false,
    globalChat: true,
    tournament: true,
    recruitment: true,
  },
};
